# Generated by Django 5.0.6 on 2024-07-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_status_options_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
