# Generated by Django 5.0.6 on 2024-06-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maker',
            new_name='CarMaker',
        ),
        migrations.RenameModel(
            old_name='Model',
            new_name='CarModel',
        ),
    ]
