# Generated by Django 5.0.6 on 2024-06-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_maker_carmaker_rename_model_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmaker',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.country'),
        ),
    ]
